"""add queue

Revision ID: ad2e3e225dd6
Revises: f7b0dc31d749
Create Date: 2025-10-23 21:17:37.225609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad2e3e225dd6'
down_revision: Union[str, Sequence[str], None] = 'f7b0dc31d749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('completed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queues_id'), 'queues', ['id'], unique=False)
    op.add_column('requests', sa.Column('queue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'requests', 'queues', ['queue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_column('requests', 'queue_id')
    op.drop_index(op.f('ix_queues_id'), table_name='queues')
    op.drop_table('queues')
    # ### end Alembic commands ###
