"""delete user mode

Revision ID: f7b0dc31d749
Revises: f79b26d720b6
Create Date: 2025-10-23 17:21:31.672121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b0dc31d749'
down_revision: Union[str, Sequence[str], None] = 'f79b26d720b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mode', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
