repository:
  name: easyvpn
  description: A VPN that is easy to use and maintain
  homepage: https://example.github.io/
  topics: vpn, python
  private: false

  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true

  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true

  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# Labels: define labels for Issues and Pull Requests
labels:
milestones:
collaborators:
  - username: stounfo
    permission: admin
  - username: GerasimovRM
    permission: admin

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
      enforce_admins: true
      required_linear_history: true
