- name: Install Docker
  block:
    - name: Install Docker
      include_role:
        name: geerlingguy.docker
      vars:
        docker_package_state: latest
  become: yes
- name: Install Docker SDK for Python3 via apt
  apt:
    name: python3-docker
    state: present
  become: yes