FROM nginx:{{ nginx_version }}

RUN rm /etc/nginx/conf.d/default.conf

COPY proxy.conf /etc/nginx/conf.d/
COPY index.html /usr/share/nginx/html/index.html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
